### PR TITLE
Starting mating addition

### PR DESCRIPTION
**Pull request by erolm-a**
Addresses #7

### CODE REVIEW

**Comment by magicicada** [comment]
Note, doesn't yet address #8 or #36

**Comment by magicicada** [comment]
@SaraJakubiak @erolm-a in trying to fix the tests I've come across an interesting problem that I think is related to the string encoding of the Cage - if I've understood correctly, it is unhappy with the fact that I've got dictionaries with tuple keys.  This is corroborated by that particular problem going away if I change my genotypes to just be strings instead of tuples.  I'd rather not do that if we can avoid it because of the way we need to pull out genotypes for breeding, but it's possible if we really need to.  

It is the current failure showing here, so if either of you two have any ideas on how best to deal with this, I'd be happy to hear?

If either of you

**Comment by anthonyohare** [comment]
Rather than have a tuple as a key could that information be encapsulated in a class? In Java/Kotlin (that I'm more familiar with) we'd create an enum/data class for the key and this could easily be encoded.
I know this is a bit more work and may be a bit overkill!

**Comment by erolm-a** [comment]
@magicicada so as far as I know the hash method for tuples is defined if and only if the hash method is defined for each type making the tuple. Tuples of strings definitely work as dictionary key so I am not sure which data type you are using for your genotypes exactly. Even though I agree it isn't the best solution as @anthonyohare said.

As for the encoding, I think a bitset would be a much better option, even though we may lose "sparsity".

**Comment by magicicada** [comment]
To be clear, I believe it's an objection of the json encoder, rather than the model code itself.

**Comment by magicicada** [comment]
Alright gang.  While there are still some todos on this branch, I'd really like to get this merged soon, and deal with those smaller todos as separate issues/branches.  The conflicts with look to be to be resolvable without much controversy.  Could I have any requests/review/etc please on anything obstructing a merge, please?
@SaraJakubiak @erolm-a

**Comment by erolm-a** [comment]
Hi, I think it'd be better if we waited until #54 got merged. The egg generation got revamped to take into account a new mating strategy. This will likely break your tests, but we can take care of fixing them while resolving the conflicts.

**Pull request merged**
